[package]
name = "count-votes"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonl = { version = "4", features = ["tokio"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
